name: flutter_math_fork
description: Fast and high-quality TeX math equation rendering with pure Dart & Flutter. 
version: 0.7.2
homepage: https://github.com/simpleclub-extended/flutter_math_fork

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ">=2.0.0+1 <3.0.0"
  provider: ^6.0.5
  meta: ^1.8.0
  collection: ^1.17.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: KaTeX_Main
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Italic.ttf
          style: italic
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Bold.ttf
          weight: 700
        - asset: lib/katex_fonts/fonts/KaTeX_Main-BoldItalic.ttf
          weight: 700
          style: italic
