name: Build
run-name: Build
on:
  workflow_dispatch: {}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      - run: cd ${{github.action_path}} && python3 build.py
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{github.action_path}}/build
