name: Build
run-name: Build
on:
  workflow_dispatch: {}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: 3.22.3 # TODO: remove this line when the issue(https://github.com/flutter/flutter/issues/153032) is fixed
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      - run: cd ${{ github.workspace }} && python3 build.py
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/build
